name = "RoME"
uuid = "91fb55c2-4c03-5a59-ba21-f4ea956187b8"
keywords = ["SLAM", "state-estimation", "mm-iSAM", "inference", "robotics"]
desc = "Non-Gaussian simultaneous localization and mapping"
version = "0.4.0"

[deps]
ApproxManifoldProducts = "9bbbb610-88a1-53cd-9763-118ce10c1f89"
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
DistributedFactorGraphs = "b5cc3c7e-6572-11e9-2517-99fb8daf2f04"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
IncrementalInference = "904591bb-b899-562f-9e6f-b8df64c7d480"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
KernelDensityEstimate = "2472808a-b354-52ea-a80e-1658a3c6056d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TransformUtils = "9b8138ad-1b09-5408-aa39-e87ed6d21b63"

[compat]
ApproxManifoldProducts = "≥ 0.1"
CoordinateTransformations = "≥ 0.5"
DistributedFactorGraphs = "≥ 0.1"
Distributions = "≥ 0.18"
DocStringExtensions = "≥ 0.7"
FileIO = "≥ 1.0"
Graphs = "≥ 0.10.3"
IncrementalInference = "^0.7.2"
JLD2 = "≥ 0.1"
KernelDensityEstimate = "≥ 0.5"
Optim = "≥ 0.16"
ProgressMeter = "≥ 0.9"
Reexport = "≥ 0.2"
Rotations = "≥ 0.11"
TransformUtils = "≥ 0.2.2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
